apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendationservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sunaofficials/cisco-mcn-cd
    targetRevision: main
    path: eks-prod/recommendationservice
  destination:
    server: https://kubernetes.default.svc
    namespace: cisco-shopping
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
