apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emailservice-hpa
  namespace: cisco-shopping
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emailservice  
  minReplicas: 1
  maxReplicas: 5  
  metrics:
  - type: Resource  
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70