apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cart-pvc
  namespace: cisco-shopping
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2