apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cart-pvc
  namespace: cisco-shopping
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
